Anthill/WebApplication1/Controllers/MatchesController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Helpers.Contracts;
using WebApplication1.Repositories.Contracts;

namespace WebApplication1.Controllers
{
    public class MatchesController : Controller
    {
        
        private readonly IMatchesRepository matchesRepository;
        private readonly IModelMapper modelMapper;
        public MatchesController(IMatchesRepository matchesRepository, IModelMapper modelMapper)
        {
            this.matchesRepository = matchesRepository;
            this.modelMapper = modelMapper;
        }

        public IActionResult TopMatch()
        {
              var result = matchesRepository.GetTopScoredMatch();
            return View(result);
        }
    }
}

Anthill/WebApplication1/Controllers/TeamsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Helpers.Contracts;
using WebApplication1.Models;
using WebApplication1.Repositories;
using WebApplication1.Repositories.Contracts;

namespace WebApplication1.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ITeamsRepository teamsRepository;
        private readonly IModelMapper modelMapper;
        public TeamsController(ITeamsRepository teamsRepository, IModelMapper modelMapper)
        {
            this.teamsRepository = teamsRepository;
            this.modelMapper = modelMapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Team> result = teamsRepository.GetAllTeamsSP();
            var resultDto = result.Select(x => this.modelMapper.MapTeamToDto(x)).ToList();
            return View(resultDto);
        }

        [HttpGet]
        public IActionResult TopScorers()
        {
            List<TopScorersSP> result = teamsRepository.GetTopScores();
            return View(result);
        }
        [HttpGet]
        public IActionResult TopConceders()
        {
            List<TopScorersSP> result = teamsRepository.GetTopConceeder();
            return View(result);
        }
    }
}

Anthill/WebApplication1/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Teams" asp-action="Index" class="nav-link text-dark" >Teams</a>
                        </li>
                         <li class="nav-item">
                            <a asp-controller="Teams" asp-action="TopScorers" class="nav-link text-dark" >TopScorers</a>
                        </li>
                          <li class="nav-item">
                            <a asp-controller="Teams" asp-action="TopConceders" class="nav-link text-dark" >TopConceders</a>
                        </li>
                        </li>
                          <li class="nav-item">
                            <a asp-controller="Matches" asp-action="TopMatch" class="nav-link text-dark" >TopScoredMatch</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>